window.esdocSearchIndex = [
  [
    "trackomatic/src/plugins/errorreportingplugin.js~errorreportingplugin",
    "class/src/plugins/errorReportingPlugin.js~ErrorReportingPlugin.html",
    "<span>ErrorReportingPlugin</span> <span class=\"search-result-import-path\">trackomatic/src/plugins/errorReportingPlugin.js</span>",
    "class"
  ],
  [
    "trackomatic/src/plugins/firstinputplugin.js~firstinputplugin",
    "class/src/plugins/firstInputPlugin.js~FirstInputPlugin.html",
    "<span>FirstInputPlugin</span> <span class=\"search-result-import-path\">trackomatic/src/plugins/firstInputPlugin.js</span>",
    "class"
  ],
  [
    "trackomatic/src/plugins/linktrackingplugin.js~linktrackingplugin",
    "class/src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin.html",
    "<span>LinkTrackingPlugin</span> <span class=\"search-result-import-path\">trackomatic/src/plugins/linkTrackingPlugin.js</span>",
    "class"
  ],
  [
    "trackomatic/src/plugin.js~plugin",
    "class/src/plugin.js~Plugin.html",
    "<span>Plugin</span> <span class=\"search-result-import-path\">trackomatic/src/plugin.js</span>",
    "class"
  ],
  [
    "trackomatic/src/trackomatic.js~trackomatic",
    "class/src/trackomatic.js~Trackomatic.html",
    "<span>Trackomatic</span> <span class=\"search-result-import-path\">trackomatic/src/trackomatic.js</span>",
    "class"
  ],
  [
    "trackomatic/src/plugins/viewporttrackingplugin.js~viewporttrackingplugin",
    "class/src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin.html",
    "<span>ViewportTrackingPlugin</span> <span class=\"search-result-import-path\">trackomatic/src/plugins/viewportTrackingPlugin.js</span>",
    "class"
  ],
  [
    "trackomatic/src/config.js~config",
    "variable/index.html#static-variable-config",
    "<span>config</span> <span class=\"search-result-import-path\">trackomatic/src/config.js</span>",
    "variable"
  ],
  [
    "trackomatic/src/plugins/errorreportingplugin.js~errorreportingplugin",
    "variable/index.html#static-variable-errorReportingPlugin",
    "<span>errorReportingPlugin</span> <span class=\"search-result-import-path\">trackomatic/src/plugins/errorReportingPlugin.js</span>",
    "variable"
  ],
  [
    "trackomatic/src/plugins/firstinputplugin.js~firstinputplugin",
    "variable/index.html#static-variable-firstInputPlugin",
    "<span>firstInputPlugin</span> <span class=\"search-result-import-path\">trackomatic/src/plugins/firstInputPlugin.js</span>",
    "variable"
  ],
  [
    "trackomatic/src/plugins/linktrackingplugin.js~linktrackingplugin",
    "variable/index.html#static-variable-linkTrackingPlugin",
    "<span>linkTrackingPlugin</span> <span class=\"search-result-import-path\">trackomatic/src/plugins/linkTrackingPlugin.js</span>",
    "variable"
  ],
  [
    "trackomatic/src/once.js~once",
    "function/index.html#static-function-once",
    "<span>once</span> <span class=\"search-result-import-path\">trackomatic/src/once.js</span>",
    "function"
  ],
  [
    "trackomatic/src/plugin.js~plugin",
    "variable/index.html#static-variable-plugin",
    "<span>plugin</span> <span class=\"search-result-import-path\">trackomatic/src/plugin.js</span>",
    "variable"
  ],
  [
    "trackomatic/src/provide.js~provideplugin",
    "function/index.html#static-function-providePlugin",
    "<span>providePlugin</span> <span class=\"search-result-import-path\">trackomatic/src/provide.js</span>",
    "function"
  ],
  [
    "trackomatic/src/trackomatic.js~trackomatic",
    "variable/index.html#static-variable-trackomatic",
    "<span>trackomatic</span> <span class=\"search-result-import-path\">trackomatic/src/trackomatic.js</span>",
    "variable"
  ],
  [
    "trackomatic/src/util.js~util",
    "variable/index.html#static-variable-util",
    "<span>util</span> <span class=\"search-result-import-path\">trackomatic/src/util.js</span>",
    "variable"
  ],
  [
    "trackomatic/src/plugins/viewporttrackingplugin.js~viewporttrackingplugin",
    "variable/index.html#static-variable-viewportTrackingPlugin",
    "<span>viewportTrackingPlugin</span> <span class=\"search-result-import-path\">trackomatic/src/plugins/viewportTrackingPlugin.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/src/__tests__/plugin.test.js.html#lineNumber4",
    "Plugin",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/plugin.test.js.html#lineNumber23",
    "Plugin provides a method that proxies Trackomatic.track() as this.track()",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/plugin.test.js.html#lineNumber17",
    "Plugin stores a reference to the instance of Trackomatic as this.__trackomatic__",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/trackomatic.test.js.html#lineNumber4",
    "Trackomatic",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/trackomatic.test.js.html#lineNumber27",
    "Trackomatic converts configured `files` and `networks` options into RegExp objects",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/trackomatic.test.js.html#lineNumber20",
    "Trackomatic extends default config settings with provided options",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/trackomatic.test.js.html#lineNumber48",
    "Trackomatic prepends the prefix to the Category field of tracking calls if options.prefix is not empty",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/trackomatic.test.js.html#lineNumber13",
    "Trackomatic stores the provided tracker",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/trackomatic.test.js.html#lineNumber35",
    "Trackomatic warns when dataLayer is undefined if options.debug is true",
    "test"
  ],
  [
    "src/__tests__/plugin.test.js",
    "file/src/__tests__/plugin.test.js.html",
    "src/__tests__/plugin.test.js",
    "file"
  ],
  [
    "src/__tests__/plugin.test.js",
    "test-file/src/__tests__/plugin.test.js.html",
    "src/__tests__/plugin.test.js",
    "testFile"
  ],
  [
    "src/__tests__/trackomatic.test.js",
    "test-file/src/__tests__/trackomatic.test.js.html",
    "src/__tests__/trackomatic.test.js",
    "testFile"
  ],
  [
    "src/__tests__/trackomatic.test.js",
    "file/src/__tests__/trackomatic.test.js.html",
    "src/__tests__/trackomatic.test.js",
    "file"
  ],
  [
    "src/__tests__/util.test.js",
    "file/src/__tests__/util.test.js.html",
    "src/__tests__/util.test.js",
    "file"
  ],
  [
    "src/__tests__/util.test.js",
    "test-file/src/__tests__/util.test.js.html",
    "src/__tests__/util.test.js",
    "testFile"
  ],
  [
    "src/config.js",
    "file/src/config.js.html",
    "src/config.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/once.js",
    "file/src/once.js.html",
    "src/once.js",
    "file"
  ],
  [
    "src/plugin.js",
    "file/src/plugin.js.html",
    "src/plugin.js",
    "file"
  ],
  [
    "src/plugin.js~plugin#constructor",
    "class/src/plugin.js~Plugin.html#instance-constructor-constructor",
    "src/plugin.js~Plugin#constructor",
    "method"
  ],
  [
    "src/plugin.js~plugin#install",
    "class/src/plugin.js~Plugin.html#instance-method-install",
    "src/plugin.js~Plugin#install",
    "method"
  ],
  [
    "src/plugin.js~plugin#track",
    "class/src/plugin.js~Plugin.html#instance-method-track",
    "src/plugin.js~Plugin#track",
    "method"
  ],
  [
    "src/plugins/errorreportingplugin.js",
    "file/src/plugins/errorReportingPlugin.js.html",
    "src/plugins/errorReportingPlugin.js",
    "file"
  ],
  [
    "src/plugins/errorreportingplugin.js~errorreportingplugin#install",
    "class/src/plugins/errorReportingPlugin.js~ErrorReportingPlugin.html#instance-method-install",
    "src/plugins/errorReportingPlugin.js~ErrorReportingPlugin#install",
    "method"
  ],
  [
    "src/plugins/errorreportingplugin.js~errorreportingplugin#oldonerror",
    "class/src/plugins/errorReportingPlugin.js~ErrorReportingPlugin.html#instance-member-oldonerror",
    "src/plugins/errorReportingPlugin.js~ErrorReportingPlugin#oldonerror",
    "member"
  ],
  [
    "src/plugins/firstinputplugin.js",
    "file/src/plugins/firstInputPlugin.js.html",
    "src/plugins/firstInputPlugin.js",
    "file"
  ],
  [
    "src/plugins/firstinputplugin.js~firstinputplugin#firstinputrecorded",
    "class/src/plugins/firstInputPlugin.js~FirstInputPlugin.html#instance-member-firstInputRecorded",
    "src/plugins/firstInputPlugin.js~FirstInputPlugin#firstInputRecorded",
    "member"
  ],
  [
    "src/plugins/firstinputplugin.js~firstinputplugin#getmouseevent",
    "class/src/plugins/firstInputPlugin.js~FirstInputPlugin.html#instance-method-getMouseEvent",
    "src/plugins/firstInputPlugin.js~FirstInputPlugin#getMouseEvent",
    "method"
  ],
  [
    "src/plugins/firstinputplugin.js~firstinputplugin#install",
    "class/src/plugins/firstInputPlugin.js~FirstInputPlugin.html#instance-method-install",
    "src/plugins/firstInputPlugin.js~FirstInputPlugin#install",
    "method"
  ],
  [
    "src/plugins/firstinputplugin.js~firstinputplugin#onkeyboardinput",
    "class/src/plugins/firstInputPlugin.js~FirstInputPlugin.html#instance-method-onKeyboardInput",
    "src/plugins/firstInputPlugin.js~FirstInputPlugin#onKeyboardInput",
    "method"
  ],
  [
    "src/plugins/firstinputplugin.js~firstinputplugin#onmouseinput",
    "class/src/plugins/firstInputPlugin.js~FirstInputPlugin.html#instance-method-onMouseInput",
    "src/plugins/firstInputPlugin.js~FirstInputPlugin#onMouseInput",
    "method"
  ],
  [
    "src/plugins/firstinputplugin.js~firstinputplugin#ontouchinput",
    "class/src/plugins/firstInputPlugin.js~FirstInputPlugin.html#instance-method-onTouchInput",
    "src/plugins/firstInputPlugin.js~FirstInputPlugin#onTouchInput",
    "method"
  ],
  [
    "src/plugins/firstinputplugin.js~firstinputplugin#recordfirstinput",
    "class/src/plugins/firstInputPlugin.js~FirstInputPlugin.html#instance-method-recordFirstInput",
    "src/plugins/firstInputPlugin.js~FirstInputPlugin#recordFirstInput",
    "method"
  ],
  [
    "src/plugins/index.js",
    "file/src/plugins/index.js.html",
    "src/plugins/index.js",
    "file"
  ],
  [
    "src/plugins/linktrackingplugin.js",
    "file/src/plugins/linkTrackingPlugin.js.html",
    "src/plugins/linkTrackingPlugin.js",
    "file"
  ],
  [
    "src/plugins/linktrackingplugin.js~linktrackingplugin#createredirect",
    "class/src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin.html#instance-method-createRedirect",
    "src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin#createRedirect",
    "method"
  ],
  [
    "src/plugins/linktrackingplugin.js~linktrackingplugin#extractautotrackingattributes",
    "class/src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin.html#instance-method-extractAutoTrackingAttributes",
    "src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin#extractAutoTrackingAttributes",
    "method"
  ],
  [
    "src/plugins/linktrackingplugin.js~linktrackingplugin#getvisitdata",
    "class/src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin.html#instance-method-getVisitData",
    "src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin#getVisitData",
    "method"
  ],
  [
    "src/plugins/linktrackingplugin.js~linktrackingplugin#install",
    "class/src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin.html#instance-method-install",
    "src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin#install",
    "method"
  ],
  [
    "src/plugins/linktrackingplugin.js~linktrackingplugin#interceptvisit",
    "class/src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin.html#instance-method-interceptVisit",
    "src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin#interceptVisit",
    "method"
  ],
  [
    "src/plugins/linktrackingplugin.js~linktrackingplugin#onlinkclick",
    "class/src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin.html#instance-method-onLinkClick",
    "src/plugins/linkTrackingPlugin.js~LinkTrackingPlugin#onLinkClick",
    "method"
  ],
  [
    "src/plugins/viewporttrackingplugin.js",
    "file/src/plugins/viewportTrackingPlugin.js.html",
    "src/plugins/viewportTrackingPlugin.js",
    "file"
  ],
  [
    "src/plugins/viewporttrackingplugin.js~viewporttrackingplugin#calculateviewportchanges",
    "class/src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin.html#instance-method-calculateViewportChanges",
    "src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin#calculateViewportChanges",
    "method"
  ],
  [
    "src/plugins/viewporttrackingplugin.js~viewporttrackingplugin#install",
    "class/src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin.html#instance-method-install",
    "src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin#install",
    "method"
  ],
  [
    "src/plugins/viewporttrackingplugin.js~viewporttrackingplugin#listen",
    "class/src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin.html#instance-method-listen",
    "src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin#listen",
    "method"
  ],
  [
    "src/plugins/viewporttrackingplugin.js~viewporttrackingplugin#simpleheight",
    "class/src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin.html#instance-member-simpleHeight",
    "src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin#simpleHeight",
    "member"
  ],
  [
    "src/plugins/viewporttrackingplugin.js~viewporttrackingplugin#simplewidth",
    "class/src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin.html#instance-member-simpleWidth",
    "src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin#simpleWidth",
    "member"
  ],
  [
    "src/plugins/viewporttrackingplugin.js~viewporttrackingplugin#trackviewportchanges",
    "class/src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin.html#instance-method-trackViewportChanges",
    "src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin#trackViewportChanges",
    "method"
  ],
  [
    "src/plugins/viewporttrackingplugin.js~viewporttrackingplugin#viewportratio",
    "class/src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin.html#instance-member-viewportRatio",
    "src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin#viewportRatio",
    "member"
  ],
  [
    "src/plugins/viewporttrackingplugin.js~viewporttrackingplugin#viewportsize",
    "class/src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin.html#instance-member-viewportSize",
    "src/plugins/viewportTrackingPlugin.js~ViewportTrackingPlugin#viewportSize",
    "member"
  ],
  [
    "src/provide.js",
    "file/src/provide.js.html",
    "src/provide.js",
    "file"
  ],
  [
    "src/shouldprovide.js",
    "file/src/shouldProvide.js.html",
    "src/shouldProvide.js",
    "file"
  ],
  [
    "src/trackparams.js",
    "file/src/trackParams.js.html",
    "src/trackParams.js",
    "file"
  ],
  [
    "src/trackomatic.js",
    "file/src/trackomatic.js.html",
    "src/trackomatic.js",
    "file"
  ],
  [
    "src/trackomatic.js~trackomatic#boot",
    "class/src/trackomatic.js~Trackomatic.html#instance-method-boot",
    "src/trackomatic.js~Trackomatic#boot",
    "method"
  ],
  [
    "src/trackomatic.js~trackomatic#config",
    "class/src/trackomatic.js~Trackomatic.html#instance-member-config",
    "src/trackomatic.js~Trackomatic#config",
    "member"
  ],
  [
    "src/trackomatic.js~trackomatic#constructor",
    "class/src/trackomatic.js~Trackomatic.html#instance-constructor-constructor",
    "src/trackomatic.js~Trackomatic#constructor",
    "method"
  ],
  [
    "src/trackomatic.js~trackomatic#notifyga",
    "class/src/trackomatic.js~Trackomatic.html#instance-method-notifyGA",
    "src/trackomatic.js~Trackomatic#notifyGA",
    "method"
  ],
  [
    "src/trackomatic.js~trackomatic#notifygtm",
    "class/src/trackomatic.js~Trackomatic.html#instance-method-notifyGTM",
    "src/trackomatic.js~Trackomatic#notifyGTM",
    "method"
  ],
  [
    "src/trackomatic.js~trackomatic#options",
    "class/src/trackomatic.js~Trackomatic.html#instance-member-options",
    "src/trackomatic.js~Trackomatic#options",
    "member"
  ],
  [
    "src/trackomatic.js~trackomatic#prefix",
    "class/src/trackomatic.js~Trackomatic.html#instance-method-prefix",
    "src/trackomatic.js~Trackomatic#prefix",
    "method"
  ],
  [
    "src/trackomatic.js~trackomatic#prepare",
    "class/src/trackomatic.js~Trackomatic.html#instance-method-prepare",
    "src/trackomatic.js~Trackomatic#prepare",
    "method"
  ],
  [
    "src/trackomatic.js~trackomatic#track",
    "class/src/trackomatic.js~Trackomatic.html#instance-method-track",
    "src/trackomatic.js~Trackomatic#track",
    "method"
  ],
  [
    "src/trackomatic.js~trackomatic#tracker",
    "class/src/trackomatic.js~Trackomatic.html#instance-member-tracker",
    "src/trackomatic.js~Trackomatic#tracker",
    "member"
  ],
  [
    "src/trackomatic.js~trackomatic#util",
    "class/src/trackomatic.js~Trackomatic.html#instance-member-util",
    "src/trackomatic.js~Trackomatic#util",
    "member"
  ],
  [
    "src/util.js",
    "file/src/util.js.html",
    "src/util.js",
    "file"
  ],
  [
    "",
    "test-file/src/__tests__/util.test.js.html#lineNumber4",
    "util",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/util.test.js.html#lineNumber40",
    "util callOnce()",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/util.test.js.html#lineNumber41",
    "util callOnce() returns a wrapped function that is guarded from being invoked more than once",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/util.test.js.html#lineNumber6",
    "util createAnchor()",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/util.test.js.html#lineNumber7",
    "util createAnchor() creates an anchor node and sets the href",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/util.test.js.html#lineNumber16",
    "util getPathname()",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/util.test.js.html#lineNumber17",
    "util getPathname() extracts the pathname from a url",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/util.test.js.html#lineNumber23",
    "util slugify()",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/util.test.js.html#lineNumber24",
    "util slugify() converts a string with spaces into a suitable all lowercase slug",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/util.test.js.html#lineNumber34",
    "util slugify() converts double hyphens to single hyphens and prunes hypens from the start and end",
    "test"
  ],
  [
    "",
    "test-file/src/__tests__/util.test.js.html#lineNumber29",
    "util slugify() removes non-word characters but leaves numbers intact",
    "test"
  ]
]